services:
  app:
    build:
      dockerfile: 'Dockerfile'
      args:
        SRC_DIR: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/var/www/html:cached'
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
    networks:
      - localnet
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - localnet
networks:
  localnet:
    driver: bridge
volumes:
  mysql_data:
